# Generated by Django 6.1 on 2026-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='app name')),
                ('field_name', models.CharField(max_length=100, verbose_name='field name')),
                ('field_value', models.TextField(verbose_name='field value')),
            ],
            options={
                'verbose_name': 'Config parameter',
                'verbose_name_plural': 'Config parameters',
                'ordering': ('app_name', 'field_name'),
            },
        ),
    ]
